sudo: false
language: node_js
node_js:
  - '8'
before_install:
  - npm install -g codecov
script:
  - npm run test:bs
after_success:
  - codecov
after_failure:
  - codecov
env:
  global:
    - secure: NIJLpbknnA4OVT1kGa9tgty4HszgKZ4YXGshruQTU8CqXOWYSNm9TnBrmAzJZhz6q4CgYqWDoLYr6ZAljAV15VTp5y6aFB6wOrjbwSMDMuvNQrioE3tDx5XNFXJjB4AfC8Ni0ZxpRTRLiy9MRCsyEerGrWEXbyUaI3bpvU1GrfSPqUCtFrpGmmyxIaRFZ26vp4LGGnKlk1xPt9BBDzJXE8SWIHpme3f/4AA40s1VyO8ZBboI0NDe8PQr5IZ2S8R+7TCbSjtRup4I7O1UK0aeL1bhvoFG/s1V4T5e8E1sMRFsvSKN3fdVhIGE7Q9f+DIa51bO4fme+I770Pgbeva+WPJs/nGH1v6TsNQOYGD4GPDB1gW4RAwAbs+AdJ9mafUMCtQUmjr/KjUeYF+ccUWnZh6fpP0cWiDAbB8v/7l9zudHjmJg0Jchy8MRkllMnnKQFF40EJMH9s7tvkyub9h9EexA9zXTPLwy/t/XbrsaHEzIJPpg1ynFE56tUKI9byjYkbROvP7ECb424AIn8svtnIzVCIwM4+333hJ/S+xlXq3KJnrBQ0gSH7f/ZkOI8yONNWlJQYckNmaKH8Ry5RRgp7TawigeNB5HGWy+FAJcjUpgLAPxfQGU6vTl9iy9amvWz//Qyhqfs+nmeP1nPN1Cf+D1xbr2TDeb0HGy/r7XMnc=
    - secure: R2SJ7cFiZJHKxDH2DYD+PKUGY2snHU7yO8W5glTqQw9dLgl7EJLUdS4RmTmwnMNFkc/yrTNsYsZGdq3BOYAl9zN6uUsFM1X00EnzseCzIk76AE/cxfjH+kk+ktaoyMTJz3CSk3u7pSqFCG5GSUvDyevkQflWcb7EfuDFXCSV3V40hgTZPYqrOfECDo287JSup+AMJ8bFWAWGSR/PdVz/41yKKHhW5JT34W1NuWjEYuWnowM7kTWmp6wk8zNTpaf39PXK9I8RPksoyA4wZWV1Shwpl+slTTw4RbGxW6uno0VdYUwc7+FPFocaFbmvB7irOyqQ0GJhufrofjeihSsNWqcSIcGvRzNwew+k3KqC+EDNKmiL5LygZ/jFiQMfuDo9i5io/dTuRRyU7Xwe9q0QKx9WWnoSbNToWCGp860c2zyakgwuiNZCNG5SzH3iUfu5y+fRrCPQ+AXiO4cIeIaqQkMXb9RMxR22ui5u8G6kKnraOyYi70NynbwvaBWPfkXkbJaw+uzbeIof6zKlJuKrmKlXPJCs7EqIfFpNKDOVH0HBCbyrPjlTeiGaoTJaO5z4rL2X6hYsmwnHepMr9sFS8DkgdWGgn401W/ZpMppUCvlgOean/AXLZI/FnvrNPCKQ6JLVDqsD/pJ+dsqZLQQno0WjpIyLHSN1u3okMKxjEns=
deploy:
  provider: npm
  email: npm@t-code.pl
  api_key:
    secure: JR7trCwCyZFtEQWKC+hlMUHVZGUGBbptSfcF52SYbVb2OSFMf+3m75A0Rvz7Tto7Cc9ZTfv4Sk8SHgr/OyPEER+aEts/3hvxcfU2IgssQ+phbs70kJQ21g3DFtMdJKKfRBE+UUT8GtyrDEYPNm2BgLXK6/HoFR9o2u6Ay5bbRn3GbP7zMqz5KI4NFQHvoTNLhzKtAEp6PInTOWpXuS5Lb5UloypBOBBMxnNZ6A0GZhBPixl+WGYkrmGTUG5bjessFS3iViBDkFn09fxM4N63BRpLkViiGT1APp/1RFAKc92OY6o8pcB3qXnUqcRhozVu85YAGINJ39829KXgP/7geVQs2lMbuaUswFDlW29cdr+ucGp5La2vQDUkNUbYAZt1Wl+0L+LvzX665HpofyMhyZNOvTRgVKHFbAWWnMGM61ppzszo1+lhHGu0Hc8k0YflSoHleDUVYIwTCZU6QzkrsXj8ulE3AErvONXTE5NFYhbWeqa2BBlWYT4P06JW9VAIHjxZlV69fDxNaLDXusD87vaNtFXpKsM5ukEGvBRD8U1g+VyIA7XbJuguz6xAmimjb+k68vmLaJpjfCAE+lfP0jw1mddsv9Kig83UZaWaGKkBtjbftRoOK2XxsG5RiVWGuGv5CXKR1YPYIY34O4XiaIcW0DqcP4Myk1n3W8KraHE=
  on:
    tags: true
    repo: hypermedia-app/alcaeus-forms
  skip_cleanup: true
